feat: add geminiAI
institute-atri/deep pull request #37
Opened 2024-05-16 21:14 UTC by nicholasboari

## Getting Started

- Get an API key https://ai.google.dev/gemini-api/docs/api-key?hl=pt-br
- Go to application.yml and set your key
![image](https://github.com/institute-atri/deep/assets/44304317/ddcdcb54-763e-4f98-b238-3b8ab41cefd9)
 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

Issue Number: #36 

## PR Type

What kind of change does this PR introduce?

Add GeminiAI service

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior? (Optional)

## What is the new behavior?

## Other information (Optional)

2024-05-16 22:15 UTC, rafael-dev2021 requested changes
The code needs more testing.

2024-05-22 23:51 UTC, ygorsimoes requested changes
....

2024-05-23 00:01 UTC, ygorsimoes requested changes

2024-05-23 00:01 UTC, ygorsimoes commented on src/main/java/org/instituteatri/deep/service/ChatService.java
>  import org.slf4j.Logger;
Test lib

2024-05-23 22:28 UTC, rafael-dev2021 requested changes

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/infrastructure/security/AppConfigTemplate.java
> +public class AppConfigTemplate {
Create config package within the infrastructure package for the configuration classes.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
>          OccurrenceResponseDTO occurrenceResponse = occurrenceService.getById(occurrenceId);
Code repetition on lines 44-55 and 66-67

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
>  public class ChatService {
Rename the methods of the class to make it clearer and more objective what they do.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
> -    public OllamaApi.ChatResponse generate(ChatRequestDTO request, String occurrenceId) {
Dividing responsibilities into smaller, clearer methods can improve the readability and maintainability of the code.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
> +    public ChatResponseDTO generateGemini(ChatRequestDTO request, String occurrenceId) {
Dividing responsibilities into smaller, clearer methods can improve the readability and maintainability of the code.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
> +            System.out.println("Request failed with status code: " + response.getStatusCode());
Replace System.out.println with LOGGER.error or a custom exception to maintain consistency and improve error control.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
>  public class ChatService {
Improve the identification of methods with line breaks.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/ChatService.java
>      private String model;
Only declared property?

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/MessageService.java
Just a note: if this MessageService class doesn't scale in the future of the project, wouldn't it be more feasible to create the saveOllama and saveGemini methods within the ChatService class itself?
Just an observation!

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/test/java/org/instituteatri/deep/controller/ChatControllerTest.java
If possible, add 2 tests for each endpoint, 1 success and 1 error.

2024-05-23 22:28 UTC, rafael-dev2021 commented on src/test/java/org/instituteatri/deep/service/ChatServiceTest.java
Change the sentences from Portuguese to English to meet the project's development standards and, if possible, add two tests for each method.

2024-05-23 22:31 UTC, rafael-dev2021 requested changes

2024-05-23 22:31 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/model/Role.java
> +public enum Role {
Add a clear and objective name for the enum; just "Role" is too generic.

2024-05-28 17:10 UTC, rafael-dev2021 approved these changes
LGTM

2024-05-29 16:04 UTC, blackcrw approved these changes
LGTM

2024-06-03 12:57 UTC, george-prado approved these changes
LGTM.

2024-06-06 23:07 UTC, ygorsimoes approved these changes
Good!

2024-06-06 23:08 UTC, merged