feat: versioning documents and evidences enpoints and refactor routes
institute-atri/deep pull request #50
Opened 2024-05-24 22:07 UTC by wendoxx

2024-05-24 22:54 UTC, wendoxx commented
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Issue Number: N/A

## PR Type

What kind of change does this PR introduce?

<!-- Please check the one that applies to this PR using "x". -->

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior? (Optional)

<!-- Please describe the current behavior that you are modifying, or link to a relevant issue. -->

## What is the new behavior?
Just renamed cases for occurrence and changed endpoint routes.
Some methods like FindByCaseID have also been renamed to FindByOccurrenceId. 
<!-- Please describe the new behavior after your modifications. -->

## Other information (Optional)

<!-- Any other information that is important to this PR such as screenshots of how the component looks before and after the change. -->

2024-05-25 20:35 UTC, rafael-dev2021 requested changes

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/DocumentsController.java
>      public ResponseEntity<DocumentsResponseDTO> getDocumentById(@PathVariable String id) {
Add a more descriptive endpoint name, for example, /find-document/{id}

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/DocumentsController.java
> +    @DeleteMapping("/{id}")
Add a more descriptive endpoint name, for example, /delete/{id}

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/DocumentsController.java
> +    @GetMapping("/{occurrenceId}")
Add a more descriptive endpoint name, for example, /find-ocurrence/{id}

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/EvidencesController.java
> +    @GetMapping("/{id}")
Add a more descriptive endpoint name, for example, /find-evidence/{id}

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/EvidencesController.java
> +    @DeleteMapping("/{id}")
Add a more descriptive endpoint name, for example, /delete/{id}

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/EvidencesController.java
> +    @GetMapping("/{occurrenceId}")
Add a more descriptive endpoint name, for example, /find-occurrence/{id}

2024-05-25 20:35 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/DocumentsService.java
There are code repetitions in the updateDocumentsById and createDocuments methods; if possible, create an auxiliary method to avoid repetition.

2024-05-27 23:56 UTC, wendoxx commented
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Issue Number: N/A

## PR Type

What kind of change does this PR introduce?

<!-- Please check the one that applies to this PR using "x". -->

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior? (Optional)

<!-- Please describe the current behavior that you are modifying, or link to a relevant issue. -->

## What is the new behavior?
Following the requested changes, the DocumentsService and EvidencesService have been refactored. They now have an auxiliary method for updateDocumentsById, updateEvidencesById, createDocuments, and createEvidences.<!-- Please describe the new behavior after your modifications. -->

## Other information (Optional)
![Screenshot from 2024-05-27 20-40-48](https://github.com/institute-atri/deep/assets/134612039/6de5cc1c-2389-4483-b79e-6ad7a693daed)
![Screenshot from 2024-05-27 20-40-57](https://github.com/institute-atri/deep/assets/134612039/95f6b1ac-ac84-47c6-9e7b-32de6abf249a)
![Screenshot from 2024-05-27 20-41-02](https://github.com/institute-atri/deep/assets/134612039/a39487a2-e95d-43e3-8c41-46cb50d8ef86)

<!-- Any other information that is important to this PR such as screenshots of how the component looks before and after the change. -->

2024-05-28 17:02 UTC, rafael-dev2021 approved these changes
LGTM

2024-05-29 17:01 UTC, davidfontesfelix approved these changes
LGTM

2024-05-31 11:39 UTC, AllanPeterson approved these changes
LGTM.

2024-05-31 16:22 UTC, merged