Feat: create defendant endpoint
institute-atri/deep pull request #61
Opened 2024-06-06 00:44 UTC by NicollyRamos

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Issue Number: #54 

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior? (Optional)

Enpoints without swagger documentation.

## What is the new behavior?

## Other information (Optional)

2024-06-07 03:22 UTC, rafael-dev2021 requested changes

2024-06-07 03:22 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/DefendantController.java
> +    @GetMapping("/{id}")
Specify the return type on this route, for example, “find/{id}”

2024-06-07 03:22 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/controller/DefendantController.java
> +    @DeleteMapping("/{id}")
Specify the return type on this route, for example, “delete/{id}”

2024-06-07 03:22 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/DefendantService.java
> +    public DefendantDTO save(DefendantDTO defendantDTO){
Specify the name of the method more explicitly

2024-06-07 03:22 UTC, rafael-dev2021 commented on src/main/java/org/instituteatri/deep/service/DefendantService.java
> +    public void delete(String id){
Specify the name of the method more explicitly

2024-06-11 01:59 UTC, rafael-dev2021 approved these changes
LGTM

2024-06-12 21:29 UTC, Rpkevin approved these changes
LGTM

2024-06-13 03:07 UTC, blkzy approved these changes
LGTM

2024-06-13 20:11 UTC, merged